### ISSUE TITLE
bug: nested test folder may not work

### ISSUE THREAD

**Issue by henryiii** [utgwkk/pytest-github-actions-annotate-failures#19]
If you have a test in a subfolder, it seems like it does not get the full path yet for the annotations. I have a `pytest.ini` in `tests/test_python_package`, and the path reported _may_ be `test_sdist.py` instead of `tests/test_python_package/test_sdist.py`.

**Comment by speth** [comment]
I have what I think is a similar issue, where my tests are run from copies in a `build` directory because I am compiling an extension module, and want to keep the source directory clean. But of course, the paths reported when `pytest` runs are for the `build` directory, which is not part of the repository.

It would be nice to have some way to provide a mapping between these locations so the annotations could be properly shown.

**Comment by utgwkk** [comment]
I have just published [version 0.1.3](https://pypi.org/project/pytest-github-actions-annotate-failures/0.1.3/) which includes #29.
